[project]
name = "scadpy-workspace"
version = "0.1.0"
description = "Monorepo for Scadpy tools"
requires-python = ">=3.12"
dependencies = []

[tool.uv.workspace]
members = ["packages/python/solid/*"]
