[project]
name = "slide-labels"
version = "0.1.0"
description = "Slide labels generator"
requires-python = ">=3.12"
dependencies = [
    "solidpython2>=2.1.0",
    "pyyaml>=6.0.3",
]

[project.scripts]
generate-labels = "slide_labels.generate_labels:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
